"use client";

/**
 * Screen 5: Auto-Generated ROI Email Preview.
 * Shows what the weekly email looks like in-app.
 * Sent every Monday 8am — primary retention tool in Months 1-3.
 */
import { useEffect, useState } from "react";
import { analyticsApi } from "@/lib/api";

function formatCurrency(n: number): string {
  return n >= 1000 ? `$${(n / 1000).toFixed(0)}K` : `$${n.toFixed(0)}`;
}

export default function RoiEmailPage() {
  const [roi, setRoi] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    analyticsApi
      .roiSummary()
      .then(setRoi)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-teal-500 animate-pulse">Loading your ROI data…</div>
      </div>
    );
  }

  const proposals = roi?.proposals_this_week ?? 0;
  const wins = roi?.wins_this_week ?? 0;
  const hours = roi?.hours_saved ?? 0;
  const revenue = roi?.revenue_attributed_usd ?? 0;
  const sc = roi?.switching_cost ?? {};
  const switchingCost = sc.total_cost ?? 0;
  const humanHours = sc.human_hours ?? 0;
  const proposalsIndexed = sc.proposals_indexed ?? 0;
  const milestone = sc.milestone ?? "onboarding";

  return (
    <div className="min-h-screen bg-gray-100 flex flex-col items-center py-10 px-4">
      <div className="w-full max-w-2xl">
        <div className="text-center mb-6">
          <span className="text-2xl font-bold text-teal-600">Draftly</span>
          <p className="text-sm text-gray-500 mt-1">Weekly ROI Report Preview</p>
        </div>

        {/* Email card */}
        <div className="bg-white rounded-2xl shadow-sm overflow-hidden border border-gray-100">
          {/* Email header */}
          <div className="bg-gray-900 px-6 py-5">
            <div className="text-teal-400 font-bold text-xl mb-1">Draftly</div>
            <div className="text-gray-400 text-sm">Your Weekly Intelligence Report</div>
          </div>

          <div className="p-6 space-y-5">
            <h2 className="text-xl font-bold text-gray-900">
              Your Firm — Week in Review
            </h2>

            {/* This week's activity */}
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-5">
              <h3 className="text-blue-700 font-semibold text-sm mb-3">📊 This Week</h3>
              <div className="space-y-2">
                {[
                  ["Proposals generated", proposals],
                  ["Hours saved", `${hours.toFixed(1)} hrs`],
                  ["Proposals marked Won", wins],
                  ["Revenue attributed", formatCurrency(revenue)],
                ].map(([label, value]) => (
                  <div key={String(label)} className="flex justify-between text-sm">
                    <span className="text-gray-600">{label}</span>
                    <span className="font-bold text-gray-900">{value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Context-Mapper Moat */}
            <div className="bg-amber-50 border border-amber-100 rounded-xl p-5">
              <h3 className="text-amber-700 font-semibold text-sm mb-3">🔒 Your Context-Mapper Moat</h3>
              <div className="space-y-2">
                {[
                  ["Proposals indexed", proposalsIndexed],
                  ["Institutional knowledge", `${humanHours} hours`],
                  ["Cost to rebuild elsewhere", formatCurrency(switchingCost)],
                  ["Moat milestone", <span key="m" className="capitalize">{milestone}</span>],
                ].map(([label, value]) => (
                  <div key={String(label)} className="flex justify-between text-sm">
                    <span className="text-gray-600">{label}</span>
                    <span className="font-bold text-gray-900">{value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* CTA */}
            <div className="text-center py-2">
              <a
                href="/dashboard"
                className="inline-block bg-teal-500 hover:bg-teal-400 text-white px-8 py-3 rounded-lg font-bold text-sm transition-colors"
              >
                Generate a Proposal →
              </a>
            </div>

            {/* Footer */}
            <div className="text-center text-xs text-gray-400 border-t border-gray-100 pt-4">
              Draftly ·{" "}
              <a href="#" className="text-gray-400 hover:underline">
                Unsubscribe
              </a>
              <br />
              This email was auto-generated by Draftly&apos;s ROI tracking system.
            </div>
          </div>
        </div>

        {/* Meta info */}
        <div className="mt-6 text-center text-xs text-gray-500 space-y-1">
          <p>This preview shows your actual data from the last 7 days.</p>
          <p>
            Live version sent every Monday 8am to all Professional tier customers.
          </p>
        </div>
      </div>
    </div>
  );
}
